### ISSUE TITLE
In iphone shows error maximum call stack exceeded error while importing country-sate-city ,but working in android , window and mac 

### ISSUE THREAD

**Issue by shahidforsdlc** [harpreetkhalsagtbit/country-state-city#184]
```
// LocationSelector.js
import React, { useState, useEffect } from 'react';
import { Select, Form, Input } from 'antd';
import { State, City } from 'country-state-city';

const { Option } = Select;

const LocationSelector = ({ form }) => {
  const [states, setStates] = useState([]);
  const [cities, setCities] = useState([]);
  const [selectedState, setSelectedState] = useState(null);

  useEffect(() => {
    const statesData = State.getStatesOfCountry('US');
    setStates(statesData);
  }, []);

  const handleStateChange = (value) => {
    setSelectedState(value);
    const selectedStateObj = states.find(state => state.name === value);
    const citiesData = City.getCitiesOfState('US', selectedStateObj.isoCode);
    setCities(citiesData);
    form.setFieldsValue({ city: null }); // Reset city field
  };

  const validateZipCode = (rule, value) => {
    const zipCodeRegex = /^[0-9]{5}(?:-[0-9]{4})?$/;
    // const zipCodeRegex = /^\d{5}$/;
    if (value && !zipCodeRegex.test(value)) {
      return Promise.reject('Invalid ZIP code! Please enter a 5-digit or 9 digit ZIP code. Example 12345 or 12345-1234');
    }
    return Promise.resolve();
  };

  return (
    <>
     <Form.Item
        label="Country"
        name="country"
        initialValue="USA"
        rules={[{ required: true, message: 'Please select a country!' }]}
      >
        <Select
          placeholder="Select country"
          allowClear
          optionFilterProp="children"
          showSearch
          disabled
        >
          <Option value="USA">United States</Option>
        </Select>
      </Form.Item>
      <Form.Item
        name="state"
        label="State"
        rules={[{ required: true, message: 'Please select a state!' }]}
      >
        <Select
        allowClear
        optionFilterProp="children"
        showSearch
          placeholder="Select a state"
          onChange={handleStateChange}
        >
          {states.map((state) => (
            <Option key={state.name} value={state.name}>
              {state.name}
            </Option>
          ))}
        </Select>
      </Form.Item>

      <Form.Item
        name="city"
        label="City"
        rules={[{ required: true, message: 'Please select a city!' }]}
      >
        <Select
        allowClear
        optionFilterProp="children"
        showSearch
        placeholder="Select a city" disabled={!selectedState}>
          {cities.map((city) => (
            <Option key={city.name} value={city.name}>
              {city.name}
            </Option>
          ))}
        </Select>
      </Form.Item>

      <Form.Item
        name="zipCode"
        label="ZIP Code"
        rules={[
          { required: true, message: 'Please enter a ZIP code!', validateTrigger: ['onSubmit'] },
          { validator: validateZipCode, validateTrigger: ['onSubmit'] },
        ]}
      >
        <Input placeholder="Enter ZIP code" />
      </Form.Item>
    </>
  );
};

export default LocationSelector;

```

**Comment by Martin-Fenocchio** [comment]
do you have some info about this bug? I am facing the same problem

**Comment by shahidforsdlc** [comment]
I've resolved the issue by creating my own package called `usa-state-city`,
as I only need information about the USA for my project. The problem was
occurring in a Vite project using the `country-state-city` package, and it
only showed a "maximum call stack error" on iPhone. This error was due to
the large JSON file used by the package, which contains information for all
countries.

If you're using Vite instead of CRA and encountering similar issues, I
suggest either using CRA scripts or creating your own package for specific
country information. This way, you'll only include the necessary JSON data
for that country, rather than the entire world's data.

Hope it helps ,What do you think ?

**Comment by terence1990** [comment]
Getting this too, so bizzare - deffo what @shahidforsdlc large non-async JSON imports on mobile cause memory issue, will try an async approach and revert back on this issue.

**Comment by terence1990** [comment]
I fixed it this way with async:

```
const getCountries = async () => {
  const Country = await import('country-state-city/lib/country');
  const {getAllCountries} = Country.default;
  return getAllCountries().sort((a, b) => a.name.localeCompare(b.name));
};

const getCities = async (country: string, state?: string) => {
  const City = await import('country-state-city/lib/city');
  const {getCitiesOfState, getCitiesOfCountry} = City.default;
  return state ? getCitiesOfState(country, state) : getCitiesOfCountry(country) ?? [];
}
```

Since it's now async, becomes troublesome as need to run a side affect in react, so used a hook:

```
import { ICity, ICountry, IState } from 'country-state-city/lib/interface';

export const useCountriesAndCities = (props?: {
  country?: string,
  state?: string
}) => {
  const [countries, setCountries] = useState<ICountry[]>([]);
  const [cities, setCities] = useState<ICity[]>([]);

  useEffect(() => {
    getCountries().then(setCountries);
  }, []);

  useEffect(() => {
    if (props?.country && props?.state) {
      getCities(props.country, props.state).then(setCities);
    }
  }, [props?.country, props?.state]);

  const phoneCodes = useMemo(() => countries
    .map((country) => ({
      value: country.phonecode.startsWith('+')
        ? country.phonecode
        : `+${country.phonecode}`,
      label: `${country.flag} ${
        country.phonecode.startsWith('+')
          ? country.phonecode
          : `+${country.phonecode}`
      }`,
    }))
    .filter((a, i, arr) => arr.findIndex((b) => b.value === a.value) === i), [countries]);

  return {
    countries,
    cities,
    phoneCodes
  };

};
```

Related:
https://github.com/harpreetkhalsagtbit/country-state-city/issues/173
https://github.com/harpreetkhalsagtbit/country-state-city/issues/123

**Comment by modernlabrat** [comment]
This issue still exists. I don't think this package is being managed anymore...

**Comment by mzakiullahusman** [comment]
I ran into some major problems in production with this issue. As an Android user, wasnt using any emulators to test on iOS and my web app just blew up for iOS users...took me around 2-4 hours to find the culprit

**Comment by 432i** [comment]
> I fixed it this way with async:
> 
> ```
> const getCountries = async () => {
>   const Country = await import('country-state-city/lib/country');
>   const {getAllCountries} = Country.default;
>   return getAllCountries().sort((a, b) => a.name.localeCompare(b.name));
> };
> 
> const getCities = async (country: string, state?: string) => {
>   const City = await import('country-state-city/lib/city');
>   const {getCitiesOfState, getCitiesOfCountry} = City.default;
>   return state ? getCitiesOfState(country, state) : getCitiesOfCountry(country) ?? [];
> }
> ```
> 
> Since it's now async, becomes troublesome as need to run a side affect in react, so used a hook:
> 
> ```
> import { ICity, ICountry, IState } from 'country-state-city/lib/interface';
> 
> export const useCountriesAndCities = (props?: {
>   country?: string,
>   state?: string
> }) => {
>   const [countries, setCountries] = useState<ICountry[]>([]);
>   const [cities, setCities] = useState<ICity[]>([]);
> 
>   useEffect(() => {
>     getCountries().then(setCountries);
>   }, []);
> 
>   useEffect(() => {
>     if (props?.country && props?.state) {
>       getCities(props.country, props.state).then(setCities);
>     }
>   }, [props?.country, props?.state]);
> 
>   const phoneCodes = useMemo(() => countries
>     .map((country) => ({
>       value: country.phonecode.startsWith('+')
>         ? country.phonecode
>         : `+${country.phonecode}`,
>       label: `${country.flag} ${
>         country.phonecode.startsWith('+')
>           ? country.phonecode
>           : `+${country.phonecode}`
>       }`,
>     }))
>     .filter((a, i, arr) => arr.findIndex((b) => b.value === a.value) === i), [countries]);
> 
>   return {
>     countries,
>     cities,
>     phoneCodes
>   };
> 
> };
> ```
> 
> Related: [#173](https://github.com/harpreetkhalsagtbit/country-state-city/issues/173) [#123](https://github.com/harpreetkhalsagtbit/country-state-city/issues/123)

Thank you!! you saved my life

**Comment by 432i** [comment]
> Getting this too, so bizzare - deffo what [@shahidforsdlc](https://github.com/shahidforsdlc) large non-async JSON imports on mobile cause memory issue, will try an async approach and revert back on this issue.

Hi, I tried your approach and is working for country and region, but city still throwing maximum call stack exceeded error, can you help me with this? here is my code
```
export const CityOrCommuneSelect: React.FC<CityOrCommuneSelectProps> = ({ placeholder, handleSetValue, countryCode, stateCode, isClearable=false }) => {

  const [newCities, setNewCities] = useState<{ label: string; value: string }[]>([]);

  const getCities = async (country: string, state: string) => {
    const City = await import('country-state-city/lib/city');
    const {getCitiesOfState} = City.default;
    return getCitiesOfState(country, state);
  }
  
  useEffect(() => {
    const fetchCities = async () => {
      if (!countryCode || !stateCode) return;

      const fetchedCities = await getCities(countryCode, stateCode);

      const formattedCities = fetchedCities.map((val) => ({
        label: val.name,
        value: val.name,
      }));

      setNewCities(formattedCities);
    };

    fetchCities();

  }, [countryCode, stateCode]);

  return (
    <Select isClearable={isClearable} placeholder={placeholder} styles={customStyles} noOptionsMessage={() => "elige pais y región"} options={newCities} onChange={ val => handleSetValue("cityOrCommune", val?.value || '') } />
  )
}
```

**Comment by mzakiullahusman** [comment]
this repo fixes this issue ny using APIs instead of storing everything locally - now using this one anytime I need this functionality:
[https://github.com/DeepakKumarKhatri/city-state-country]

**Comment by 432i** [comment]
> this repo fixes this issue ny using APIs instead of storing everything locally - now using this one anytime I need this functionality: [https://github.com/DeepakKumarKhatri/city-state-country]

does it use the same data as this library?

**Comment by VikramSingh1994** [comment]
Hi @terence1990 ,
Country & states are working but its not working for cities. Could you please suggest if you did any other thing for cities.

```
import React, {useState, useEffect} from 'react';
import {View, StyleSheet, Text} from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import {ICountry, IState, ICity} from 'country-state-city/lib/interface';

const Location = () => {
  const [selectedCountry, setSelectedCountry] = useState('');
  const [selectedState, setSelectedState] = useState('');
  const [selectedCity, setSelectedCity] = useState('');

  const [countries, setCountries] = useState([]);
  const [states, setStates] = useState([]);
  const [cities, setCities] = useState([]);

  // Load countries once
  useEffect(() => {
    getCountries().then(setCountries);
  }, []);

  useEffect(() => {
    if (selectedCountry) {
      getStates(selectedCountry).then(setStates);
    }
  }, [selectedCountry]);

  useEffect(() => {
    if (selectedState) {
      getCities(selectedCountry, selectedState).then(setCities);
    }
  }, [selectedState]);

  const getCountries = async (): Promise<ICountry[]> => {
    const Country = await import('country-state-city/lib/country');
    const {getAllCountries} = Country.default;
    const temp = getAllCountries().sort((a, b) => a.name.localeCompare(b.name));
    return temp;
  };

  const getStates = async (country: string) => {
    const State = await import('country-state-city/lib/state');
    const {getStatesOfCountry} = State.default;
    return getStatesOfCountry(country) ?? [];
  };

  const getCities = async (country: string, state: string) => {
    console.log('Fetching cities for:', country, state);
    const City = await import('country-state-city/lib/city');
    const {getCitiesOfState} = City.default;
    const cities = getCitiesOfState(country, state) ?? [];
    console.log('Cities:', cities);
    return cities;
  };

  return (
    <View style={styles.container}>
      <Text style={styles.label}>Country</Text>
      <RNPickerSelect
        onValueChange={value => setSelectedCountry(value)}
        items={countries.map(country => ({
          label: country.name,
          value: country.isoCode,
        }))}
        value={selectedCountry}
        placeholder={{label: 'Select a country', value: null}}
      />

      <Text style={styles.label}>States</Text>
      <RNPickerSelect
        onValueChange={value => setSelectedState(value)}
        items={states.map(state => ({
          label: state.name,
          value: state.isoCode,
        }))}
        value={selectedState}
        placeholder={{label: 'Select a state', value: null}}
      />

      <Text style={styles.label}>Cities</Text>
      <RNPickerSelect
        onValueChange={value => setSelectedCity(value)}
        items={cities.map(city => ({
          label: city.name,
          value: city.isoCode,
        }))}
        value={selectedCity}
        placeholder={{label: 'Select a city', value: null}}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 16,
  },
  label: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default Location;
```

![Image](https://github.com/user-attachments/assets/f378dc5b-36ba-48bb-99f4-59f3a225afb4)

**Comment by VikramSingh1994** [comment]
> > I fixed it this way with async:
> > ```
> > const getCountries = async () => {
> >   const Country = await import('country-state-city/lib/country');
> >   const {getAllCountries} = Country.default;
> >   return getAllCountries().sort((a, b) => a.name.localeCompare(b.name));
> > };
> > 
> > const getCities = async (country: string, state?: string) => {
> >   const City = await import('country-state-city/lib/city');
> >   const {getCitiesOfState, getCitiesOfCountry} = City.default;
> >   return state ? getCitiesOfState(country, state) : getCitiesOfCountry(country) ?? [];
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since it's now async, becomes troublesome as need to run a side affect in react, so used a hook:
> > ```
> > import { ICity, ICountry, IState } from 'country-state-city/lib/interface';
> > 
> > export const useCountriesAndCities = (props?: {
> >   country?: string,
> >   state?: string
> > }) => {
> >   const [countries, setCountries] = useState<ICountry[]>([]);
> >   const [cities, setCities] = useState<ICity[]>([]);
> > 
> >   useEffect(() => {
> >     getCountries().then(setCountries);
> >   }, []);
> > 
> >   useEffect(() => {
> >     if (props?.country && props?.state) {
> >       getCities(props.country, props.state).then(setCities);
> >     }
> >   }, [props?.country, props?.state]);
> > 
> >   const phoneCodes = useMemo(() => countries
> >     .map((country) => ({
> >       value: country.phonecode.startsWith('+')
> >         ? country.phonecode
> >         : `+${country.phonecode}`,
> >       label: `${country.flag} ${
> >         country.phonecode.startsWith('+')
> >           ? country.phonecode
> >           : `+${country.phonecode}`
> >       }`,
> >     }))
> >     .filter((a, i, arr) => arr.findIndex((b) => b.value === a.value) === i), [countries]);
> > 
> >   return {
> >     countries,
> >     cities,
> >     phoneCodes
> >   };
> > 
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Related: [#173](https://github.com/harpreetkhalsagtbit/country-state-city/issues/173) [#123](https://github.com/harpreetkhalsagtbit/country-state-city/issues/123)
> 
> Thank you!! you saved my life

How you Fixed for cities

**Comment by zanndev0511** [comment]
I create a hook like this:
```
import { useEffect, useState } from "react";
import type { ICountry, IState, ICity } from "country-state-city/lib/interface";

export const useCountriesStatesCities = (countryCode?: string, stateCode?: string) => {
  const [countries, setCountries] = useState<ICountry[]>([]);
  const [states, setStates] = useState<IState[]>([]);
  const [cities, setCities] = useState<ICity[]>([]);

  useEffect(() => {
    import("country-state-city/lib/country").then((mod) => {
      const { getAllCountries } = mod.default;
      setCountries(getAllCountries().sort((a: ICountry, b: ICountry) => a.name.localeCompare(b.name)));
    });
  }, []);

  useEffect(() => {
    if (!countryCode) {
      setStates([]);
      return;
    }
    import("country-state-city/lib/state").then((mod) => {
      const { getStatesOfCountry } = mod.default;
      setStates(getStatesOfCountry(countryCode) || []);
    });
  }, [countryCode]);

  useEffect(() => {
    if (!countryCode || !stateCode) {
      setCities([]);
      return;
    }
    import("country-state-city/lib/city").then((mod) => {
      const { getCitiesOfState } = mod.default;
      setCities(getCitiesOfState(countryCode, stateCode) || []);
    });
  }, [countryCode, stateCode]);

  return { countries, states, cities };
};

```
Then using it like this:

```
import React, { useState } from 'react';
import { useCountriesStatesCities } from './hooks/useCountriesStatesCities';

const LocationForm = () => {
  const [selectedCountry, setSelectedCountry] = useState('');
  const [selectedState, setSelectedState] = useState('');

  const { countries, states, cities } = useCountriesStatesCities(selectedCountry, selectedState);

  return (
    <div>
      <select onChange={(e) => setSelectedCountry(e.target.value)}>
        <option value="">select country</option>
        {countries.map((c) => (
          <option key={c.isoCode} value={c.isoCode}>{c.name}</option>
        ))}
      </select>

      <select onChange={(e) => setSelectedState(e.target.value)} disabled={!selectedCountry}>
        <option value="">select state</option>
        {states.map((s) => (
          <option key={s.isoCode} value={s.isoCode}>{s.name}</option>
        ))}
      </select>

      <select disabled={!selectedState}>
        <option value="">select city</option>
        {cities.map((city) => (
          <option key={city.name} value={city.name}>{city.name}</option>
        ))}
      </select>
    </div>
  );
};
```
