### ISSUE TITLE
Bundle size extremely large due to inclusion of cities database

### ISSUE THREAD

**Issue by taylorthurlow** [harpreetkhalsagtbit/country-state-city#60]
Hi, I'm wondering if there are any plans to address the size of the included JSON database. Uncompressed, the countries, states, and cities databases are more than 16 megabytes, which is still more than 2.5 when fetched with a browser, gzip compressed.

This is sort of a deal-breaker for using this application in production for just countries and states, but would be 100% more usable if there were an option to exclude the cities database when one has no intention of using it. I don't know much about tree shaking and module exclusion, nor do I know how/if that would related to a big JSON document.

Maybe @dr5hn has an opinion or suggestions on this topic?

**Comment by taylorthurlow** [comment]
Opened #62 to address this

**Comment by dr5hn** [comment]
@taylorthurlow  
This looks like a critical issue, thanks for putting this up !!

It certainly needs an attention @harpreetkhalsagtbit

**Comment by TAnas0** [comment]
Interested for the same reasons. My bundle size is getting too big, I started thinking of dropping the NPM package.
Once PR #62 is released, it'd be glad to test it.

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn @taylorthurlow @TAnas0 
I will pick this up tomorrow.

**Comment by taylorthurlow** [comment]
Great to hear, thanks. I just pushed up rewritten and passing tests to #62.

**Comment by harpreetkhalsagtbit** [comment]
I have refactored all package.
Please test beta version - `npm i country-state-city@2.1.0-beta.2`

@taylorthurlow @dr5hn @TAnas0

**Comment by JakeAi** [comment]
Why was this issue closed? It didn't fix tree shaking. Bundles are still 17+mb

**Comment by cmacdonnacha** [comment]
Same here, bundle size is 17Mb.

**Comment by cmacdonnacha** [comment]
@taylorthurlow Can you verify that tree shaking now works for you?

**Comment by harpreetkhalsagtbit** [comment]
@cmacdonnacha @taylorthurlow @dr5hn 
I tested this before merging. I don't know whats wrong. I didn't get time to check this again.

Would you all please share the package version you are testing and also share some code that fails.

**Comment by cmacdonnacha** [comment]
Sure, package version is `3.0.1` and same code is

```
import { Country, State } from 'country-state-city';
console.log(Country.getAllCountries())
console.log(State.getStatesOfCountry('US'))
```

**Comment by taylorthurlow** [comment]
> @taylorthurlow Can you verify that tree shaking now works for you?

Sorry my priorities changed and I haven't switched over from my fork yet.

**Comment by mathycoder** [comment]
Hi, any updates on this?  My bundle is also over 16 MB, and it seems impossible to tree shake city.json.

**Comment by atomauro** [comment]
Same issue, mobile is not loading properly due to this JOLY bundle
